student_performance_prediction/student_performance_prediction/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.BasePageView.as_view(), name='base_page'),
    path('admin/', admin.site.urls),
    path('', include('student_prediction.urls')),
    path('', include('student_prediction2.urls')),
    # path('dashboard/', views.dash_app, name='dashboard'),  # Include the dashboard URLs
] + static(settings.MEDIA_URL, document_root =  settings.MEDIA_ROOT)

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

student_performance_prediction/student_prediction/urls.py
from django.urls import path
from . import views

app_name = 'student_prediction'

urlpatterns = [
    path('predictions/',views.prediction,name = 'prediction'),
    path('prediction_t_test/',views.prediction_t_test,name = 'prediction_t_test'),
    path('prediction_anova/',views.prediction_anova,name = 'prediction_anova'),
    path('writing_scores_vs_gender/', views.writing_scores_vs_gender, name='writing_scores_vs_gender'),
    path('reading_scores_vs_gender/', views.reading_scores_vs_gender, name='reading_scores_vs_gender'),
    path('math_scores_vs_gender/', views.math_scores_vs_gender, name='math_scores_vs_gender'),
    path('math_scores_vs_parental_education/', views.math_scores_vs_parental_education, name='math_scores_vs_parental_education'),
    path('reading_scores_vs_parental_education/', views.reading_scores_vs_parental_education, name='reading_scores_vs_parental_education'),
    path('writing_scores_vs_parental_education/', views.writing_scores_vs_parental_education, name='writing_scores_vs_parental_education'),
    path('predict_writing/', views.writing_score, name='writing_score'),
    path('predict_math/', views.math_score, name='math_score'),
    path('predict_reading/', views.reading_score, name='reading_score'),
]

student_performance_prediction/student_prediction2/urls.py
from django.urls import path
from . import views

app_name = 'student_prediction2'

urlpatterns = [
    path('predictions2/',views.prediction,name = 'prediction'),
    path('predict_performance_index/', views.predict_performance_index, name='predict_performance_index'),
    path('scatter_plot/', views.scatter_plot, name='scatter_plot'),
]

student_performance_prediction/student_performance_prediction/views.py
# student_performance_prediction/views.py

from django.shortcuts import render
from django.views.generic.base import TemplateView

class BasePageView(TemplateView):
    template_name = 'student_performance_prediction/base.html'
    

student_performance_prediction/student_performance_prediction/templates/student_performance_prediction/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Student Performance Prediction</title>
    {% comment %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {% endcomment %}
    <!-- Add this to your HTML template -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-pzjw8f+ua7Kw1TIq0v8FqFjcJ6pajs/rfdfs3SO+k6jCkvi3x5Btyf5TOqFIIc6f5T" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
        integrity="sha384-7ax8z3GzjDkfzVqHSEqFmY4uFfz5bXIlG+6Bcy5FwJ8C6Bd5Fea5Gz2ElD5z5el5z9"
        crossorigin="anonymous"></script>
</head>
<style>
    body {
            {
            % comment %
        }

        background-color: #00b4d8;

            {
            % endcomment %
        }

        background: rgb(2, 0, 36);
        background: -moz-linear-gradient(90deg, rgba(2, 0, 36, 1) 7%, rgba(87, 87, 214, 1) 53%, rgba(0, 212, 255, 1) 86%);
        background: -webkit-linear-gradient(90deg, rgba(2, 0, 36, 1) 7%, rgba(87, 87, 214, 1) 53%, rgba(0, 212, 255, 1) 86%);
        background: linear-gradient(90deg, rgba(2, 0, 36, 1) 7%, rgba(87, 87, 214, 1) 53%, rgba(0, 212, 255, 1) 86%);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#020024", endColorstr="#00d4ff", GradientType=1);
        font-family: Arial,
        sans-serif;
        margin: 0;
        /* Remove default margin to ensure full-width header and footer */
        padding: 0;
        /* Remove default padding */
    }

    /* Header styles */
    header {
        background-color: #333;
        font-color: #fff;

            {
            % comment %
        }

        background: rgb(131, 58, 180);

            {
            % endcomment %
        }

            {
            % comment %
        }

        background: linear-gradient(90deg, rgba(131, 58, 180, 1) 0%, rgba(237, 148, 148, 1) 100%, rgba(252, 176, 69, 1) 100%);

            {
            % endcomment %
        }

        color: #fff;
        padding: 1px 0;
        text-align: center;
        border-radius:10px;
    }

    nav {
        background: red;

    }

    nav ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

    nav li {
        display: inline;
        margin-right: 20px;
    }

    nav li a {
        color: white;

    }

    /* Card styles */
    .container {
        display: flex;

            {
            % comment %
        }

        flex-wrap: wrap;

            {
            % endcomment %
        }

        justify-content: center;
        align-items: center;
        height: 100%;
        width:100%;

            {
            % comment %
        }

        background-color: red;

            {
            % endcomment %
        }

        margin-top:2em;
        /* Set container height to full viewport height */
    }

    .card {
        border: 1px solid #ccc;
        /* Add a border to the card */
        width: 300px;
        margin: 20px;
        text-align: center;
        border-radius: 5px;
        padding: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);
        background-color: #fffcf2;
        display: inline-block;
        /* Make cards display inline */
        vertical-align: top;
        /* Align cards to the top of the container */
        transition: transform 0.4s;
        /* Add a smooth hover effect */
    }

    .card img {
        width: 300px; /* Set a specific width for the images */
        height: 270px; /* Maintain aspect ratio */
        border-radius: 5px;
    }

    .card h5 {
        font-size: 1.5rem;
        margin-top: 10px;

            {
            % comment %
        }

        margin-down: 10px;

            {
            % endcomment %
        }

            {
            % comment %
        }

        padding:10px;

            {
            % endcomment %
        }
    }


    .card p {
        font-size: 1.2rem;
        margin: 10px 0;
        color: #023047;
    }

    .card-button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007BFF;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
        font-weight: bold;
    }

    .card-button:hover {
        background-color: red;
    }


    /* Footer styles */
    footer {
        background-color: #333;
        color: #fff;
        padding: 10px 0;
        text-align: center;
        position: fixed;
        bottom: 0;
        /* Stick to the bottom of the page */
        width: 100%;
    }

    /* Customize your CSS as needed */
</style>

<body>
    <header>
        <h1 style = "color: white;">Student Performance Prediction</h1>
    </header>
    <div class="container">
        <div class="card" style="width: 18rem">
            <img src="{% static 'images/first.jpg'%}" class="card-img-top" alt="..." />
            <div class="card-body">
                <h5 class="card-title">Know your scores </h5>
                <p class="card-text">
                    This card will help you<strong> "predict your score in different subjects
                    based on certain criteria and conditions".</strong>
                </p>
                <a href="{% url 'student_prediction:prediction' %}" class="card-button">Score Prediction</a>
            </div>
        </div>
        <div class="card" style="width: 18rem">
            <img src="{% static 'images/second.jpg'%}" class="card-img-top" alt="..." />
            <div class="card-body">
                <h5 class="card-title">Know your Performance </h5>
                <p class="card-text">
                    This card will help you <strong>"predict your acadamic performance based on
                    certain criteria and conditions".</strong>
                </p>
                <a href="{% url 'student_prediction2:prediction' %}" class="card-button">Performance Prediction</a>
            </div>

        </div>
        <div class="card" style="width: 18rem">
            <img src="{% static 'images/second.jpg'%}" class="card-img-top" alt="..." />
            <div class="card-body">
                <h5 class="card-title">t-test ?</h5>
                <p class="card-text">
                    This card will show you<strong> "Is there any significant difference between gender and scores using t-test".</strong>
                </p>
                <a href="{% url 'student_prediction:prediction_t_test' %}" class="card-button">T- test</a>
            </div>

        </div>

        <div class="card" style="width: 18rem">
            <img src="{% static 'images/second.jpg'%}" class="card-img-top" alt="..." />
            <div class="card-body">
                <h5 class="card-title">One Way Anova ?</h5>
                <p class="card-text" style="font-size: 19px;">
                   This card will show you <strong>"Is there any significant difference between Parental Education and scores using one-way-anova".</strong>
                </p>
                <a href="{% url 'student_prediction:prediction_anova' %}" class="card-button">One Way Anova</a>
            </div>

        </div>
        {% block content %}{% endblock %}
    </div>
    <footer>
        <p>&copy; 2023 Student Performance Prediction</p>
    </footer>
</body>

</html>