student_performance_prediction/student_performance_prediction/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.BasePageView.as_view(), name='base_page'),
    path('admin/', admin.site.urls),
    path('', include('student_prediction.urls')),
    path('', include('student_prediction2.urls')),
    # path('dashboard/', views.dash_app, name='dashboard'),  # Include the dashboard URLs
] + static(settings.MEDIA_URL, document_root =  settings.MEDIA_ROOT)

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

student_performance_prediction/student_prediction/urls.py
from django.urls import path
from . import views

app_name = 'student_prediction'

urlpatterns = [
    path('predictions/',views.prediction,name = 'prediction'),
    path('prediction_t_test/',views.prediction_t_test,name = 'prediction_t_test'),
    path('prediction_anova/',views.prediction_anova,name = 'prediction_anova'),
    path('writing_scores_vs_gender/', views.writing_scores_vs_gender, name='writing_scores_vs_gender'),
    path('reading_scores_vs_gender/', views.reading_scores_vs_gender, name='reading_scores_vs_gender'),
    path('math_scores_vs_gender/', views.math_scores_vs_gender, name='math_scores_vs_gender'),
    path('math_scores_vs_parental_education/', views.math_scores_vs_parental_education, name='math_scores_vs_parental_education'),
    path('reading_scores_vs_parental_education/', views.reading_scores_vs_parental_education, name='reading_scores_vs_parental_education'),
    path('writing_scores_vs_parental_education/', views.writing_scores_vs_parental_education, name='writing_scores_vs_parental_education'),
    path('predict_writing/', views.writing_score, name='writing_score'),
    path('predict_math/', views.math_score, name='math_score'),
    path('predict_reading/', views.reading_score, name='reading_score'),
]

student_performance_prediction/student_prediction2/urls.py
from django.urls import path
from . import views

app_name = 'student_prediction2'

urlpatterns = [
    path('predictions2/',views.prediction,name = 'prediction'),
    path('predict_performance_index/', views.predict_performance_index, name='predict_performance_index'),
    path('scatter_plot/', views.scatter_plot, name='scatter_plot'),
]

student_performance_prediction/student_prediction/forms.py
# student_prediction/forms.py
from django import forms

#writing score
class ScorePredictionForm1(forms.Form):
    gender_choices = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]

    ethnicity_choices = [
        ('group A', 'Group A'),
        ('group B', 'Group B'),
        ('group C', 'Group C'),
        ('group D', 'Group D'),
        ('group E', 'Group E'),
    ]

    education_choices = [
        ("associate's degree", "Associate's Degree"),
        ("bachelor's degree", "Bachelor's Degree"),
        ('high school', 'High School'),
        ("master's degree", "Master's Degree"),
        ('some college', 'Some College'),
        ('some high school', 'Some High School'),
    ]

    lunch_choices = [
        ('free/reduced', 'Free/Reduced'),
        ('standard', 'Standard'),
    ]

    test_prep_choices = [
        ('none', 'None'),
        ('completed', 'Completed'),
    ]

    gender = forms.ChoiceField(choices=gender_choices, label='Gender')
    race_ethnicity = forms.ChoiceField(choices=ethnicity_choices, label='Race or Ethnicity')
    parental_level_of_education = forms.ChoiceField(choices=education_choices, label='Parental Level of Education')
    lunch = forms.ChoiceField(choices=lunch_choices, label='Lunch Type')
    test_preparation_course = forms.ChoiceField(choices=test_prep_choices, label='Test Preparation Course')
    math_score = forms.FloatField(label='Math Score',max_value=100,min_value=0)
    reading_score = forms.FloatField(label='Reading Score',max_value=100,min_value=0)
    
#math score
class ScorePredictionForm2(forms.Form):
    gender_choices = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]

    ethnicity_choices = [
        ('group A', 'Group A'),
        ('group B', 'Group B'),
        ('group C', 'Group C'),
        ('group D', 'Group D'),
        ('group E', 'Group E'),
    ]

    education_choices = [
        ("associate's degree", "Associate's Degree"),
        ("bachelor's degree", "Bachelor's Degree"),
        ('high school', 'High School'),
        ("master's degree", "Master's Degree"),
        ('some college', 'Some College'),
        ('some high school', 'Some High School'),
    ]

    lunch_choices = [
        ('free/reduced', 'Free/Reduced'),
        ('standard', 'Standard'),
    ]

    test_prep_choices = [
        ('none', 'None'),
        ('completed', 'Completed'),
    ]

    gender = forms.ChoiceField(choices=gender_choices, label='Gender')
    race_ethnicity = forms.ChoiceField(choices=ethnicity_choices, label='Race or Ethnicity')
    parental_level_of_education = forms.ChoiceField(choices=education_choices, label='Parental Level of Education')
    lunch = forms.ChoiceField(choices=lunch_choices, label='Lunch Type')
    test_preparation_course = forms.ChoiceField(choices=test_prep_choices, label='Test Preparation Course')
    reading_score = forms.FloatField(label='Reading Score',max_value=100,min_value=0)
    writing_score = forms.FloatField(label='Writing Score',max_value=100,min_value=0)
    
   
    
# Reading Score    
class ScorePredictionForm3(forms.Form):
    gender_choices = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]

    ethnicity_choices = [
        ('group A', 'Group A'),
        ('group B', 'Group B'),
        ('group C', 'Group C'),
        ('group D', 'Group D'),
        ('group E', 'Group E'),
    ]

    education_choices = [
        ("associate's degree", "Associate's Degree"),
        ("bachelor's degree", "Bachelor's Degree"),
        ('high school', 'High School'),
        ("master's degree", "Master's Degree"),
        ('some college', 'Some College'),
        ('some high school', 'Some High School'),
    ]

    lunch_choices = [
        ('free/reduced', 'Free/Reduced'),
        ('standard', 'Standard'),
    ]

    test_prep_choices = [
        ('none', 'None'),
        ('completed', 'Completed'),
    ]

    gender = forms.ChoiceField(choices=gender_choices, label='Gender')
    race_ethnicity = forms.ChoiceField(choices=ethnicity_choices, label='Race or Ethnicity')
    parental_level_of_education = forms.ChoiceField(choices=education_choices, label='Parental Level of Education')
    lunch = forms.ChoiceField(choices=lunch_choices, label='Lunch Type')
    test_preparation_course = forms.ChoiceField(choices=test_prep_choices, label='Test Preparation Course')
    math_score = forms.FloatField(label='Math Score',max_value=100,min_value=0)
    writing_score = forms.FloatField(label='Writing Score',max_value=100,min_value=0)

    

# Uploading CSV file for performing various tests
from django import forms

class CSVUploadForm(forms.Form):
    csv_file = forms.FileField(label='Select a CSV file')

student_performance_prediction/student_prediction/views.py
# student_prediction/views.py
import pandas as pd
import joblib
from django.shortcuts import render
from .forms import ScorePredictionForm1, ScorePredictionForm2, ScorePredictionForm3
import os
from sklearn.preprocessing import LabelEncoder

# Define label encoders for categorical features
gender_encoder = LabelEncoder()
ethnicity_encoder = LabelEncoder()
education_encoder = LabelEncoder()
lunch_encoder = LabelEncoder()
test_prep_encoder = LabelEncoder()


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MODEL_PATH1 = os.path.join(BASE_DIR, 'ml_models', 'best_student_performance_model1.pkl')
MODEL_PATH2 = os.path.join(BASE_DIR, 'ml_models', 'best_student_performance_model2.pkl')
MODEL_PATH3 = os.path.join(BASE_DIR, 'ml_models', 'best_student_performance_model3.pkl')
DATA_PATH = os.path.join(BASE_DIR, 'data', 'updated_preprocessed_dataset1.csv')

# Load the trained ML model
model1 = joblib.load(MODEL_PATH1)
model2 = joblib.load(MODEL_PATH2)
model3 = joblib.load(MODEL_PATH3)



# Create sets for all possible categories for each feature
possible_genders = set(['male', 'female'])
possible_ethnicities = set(['group A', 'group B', 'group C', 'group D', 'group E'])
possible_educations = set(["associate's degree", "bachelor's degree", 'high school', "master's degree", 'some college', 'some high school'])
possible_lunches = set(['free/reduced', 'standard'])
possible_test_preps = set(['none', 'completed'])

# Fit the label encoders on your training data
gender_encoder.fit(list(possible_genders))
ethnicity_encoder.fit(list(possible_ethnicities))
education_encoder.fit(list(possible_educations))
lunch_encoder.fit(list(possible_lunches))
test_prep_encoder.fit(list(possible_test_preps))


def prediction(request):
    # You can add any necessary logic here, if needed
    return render(request, 'student_prediction/prediction.html')

def prediction_t_test(request):
    # You can add any necessary logic here, if needed
    return render(request, 'student_prediction/prediction_t_test.html')

def prediction_anova(request):
    # You can add any necessary logic here, if needed
    return render(request, 'student_prediction/prediction_anova.html')

# writing score
def writing_score(request):
    # Load the dataset
    dataset = pd.read_csv(DATA_PATH)
    if request.method == 'POST':
        form = ScorePredictionForm1(request.POST)
        if form.is_valid():
            # Get user input from the form
            input_data = form.cleaned_data
            
            # Apply label encoding to categorical features
            input_data['gender'] = gender_encoder.transform([input_data['gender']])[0]
            input_data['race_ethnicity'] = ethnicity_encoder.transform([input_data['race_ethnicity']])[0]
            input_data['parental_level_of_education'] = education_encoder.transform([input_data['parental_level_of_education']])[0]
            input_data['lunch'] = lunch_encoder.transform([input_data['lunch']])[0]
            input_data['test_preparation_course'] = test_prep_encoder.transform([input_data['test_preparation_course']])[0]

            # Create a DataFrame with user input
            user_data = pd.DataFrame([input_data])

            # Predict the missing score using the model
            predicted_score = round(model1.predict(user_data)[0],2)

            # Append user_data to the dataset
            dataset = pd.concat([dataset, user_data], ignore_index=True)

            # Save the updated dataset
            dataset.to_csv(DATA_PATH, index=False)

            return render(request, 'student_prediction/prediction_result.html', {'predicted_score': predicted_score})
    else:
        form = ScorePredictionForm1()

    return render(request, 'student_prediction/writing.html', {'form': form})

#math score
def math_score(request):
    # Load the dataset
    dataset = pd.read_csv(DATA_PATH)
    if request.method == 'POST':
        form = ScorePredictionForm2(request.POST)
        if form.is_valid():
            # Get user input from the form
            input_data = form.cleaned_data
            
            # Apply label encoding to categorical features
            input_data['gender'] = gender_encoder.transform([input_data['gender']])[0]
            input_data['race_ethnicity'] = ethnicity_encoder.transform([input_data['race_ethnicity']])[0]
            input_data['parental_level_of_education'] = education_encoder.transform([input_data['parental_level_of_education']])[0]
            input_data['lunch'] = lunch_encoder.transform([input_data['lunch']])[0]
            input_data['test_preparation_course'] = test_prep_encoder.transform([input_data['test_preparation_course']])[0]

            # Create a DataFrame with user input
            user_data = pd.DataFrame([input_data])

            # Predict the missing score using the model
            predicted_score = round(model2.predict(user_data)[0],2)

            # Append user_data to the dataset
            dataset = pd.concat([dataset, user_data], ignore_index=True)

            # Save the updated dataset
            dataset.to_csv(DATA_PATH, index=False)

            return render(request, 'student_prediction/prediction_result.html', {'predicted_score': predicted_score})
    else:
        form = ScorePredictionForm2()

    return render(request, 'student_prediction/math.html', {'form': form})


#reading score
def reading_score(request):
    # Load the dataset
    dataset = pd.read_csv(DATA_PATH)
    if request.method == 'POST':
        form = ScorePredictionForm3(request.POST)
        if form.is_valid():
            # Get user input from the form
            input_data = form.cleaned_data
            
            # Apply label encoding to categorical features
            input_data['gender'] = gender_encoder.transform([input_data['gender']])[0]
            input_data['race_ethnicity'] = ethnicity_encoder.transform([input_data['race_ethnicity']])[0]
            input_data['parental_level_of_education'] = education_encoder.transform([input_data['parental_level_of_education']])[0]
            input_data['lunch'] = lunch_encoder.transform([input_data['lunch']])[0]
            input_data['test_preparation_course'] = test_prep_encoder.transform([input_data['test_preparation_course']])[0]

            # Create a DataFrame with user input
            user_data = pd.DataFrame([input_data])

            # Predict the missing score using the model
            predicted_score = round(model3.predict(user_data)[0],2)
            
            # Append user_data to the dataset
            dataset = pd.concat([dataset, user_data], ignore_index=True)

            # Save the updated dataset
            dataset.to_csv(DATA_PATH, index=False)

            return render(request, 'student_prediction/prediction_result.html', {'predicted_score': predicted_score})
    else:
        form = ScorePredictionForm3()

    return render(request, 'student_prediction/reading.html', {'form': form})





# plots




### t-test
from django.shortcuts import render
import pandas as pd
import scipy.stats as stats
import numpy as np

def writing_scores_vs_gender(request):
    # Load the dataset from the 'data' folder
    dataset = pd.read_csv('data/stud.csv')

    # Perform the t-test for writing scores vs. gender
    gender = dataset['gender']
    writing_score = dataset['writing_score']

    t_test_result = stats.ttest_ind(writing_score[gender == 'male'], writing_score[gender == 'female'])
   
    female_mean = np.mean(writing_score[gender == 'female'])
    male_mean = np.mean(writing_score[gender == 'male']) 
    
    # Define null hypothesis (H0) and alternative hypothesis (H1)
    null_hypothesis = "There is no significant difference in the mean writing scores between male and female students."
    alternative_hypothesis = "There is a significant difference in the mean writing scores between male and female students."

    # Determine the result based on the p-value
    alpha = 0.05  # Set your significance level
    p_value = t_test_result.pvalue
    if p_value < alpha:
        hypothesis_result = "Reject H0"
    else:
        hypothesis_result = "Fail to Reject H0"

    context = {
        't_test_result': t_test_result,
        'test_name': "Writing Scores vs. Gender",
        'score': 'Writing',
        'female_mean':female_mean,
        'male_mean':male_mean,
        'null_hypothesis': null_hypothesis,
        'alternative_hypothesis': alternative_hypothesis,
        'hypothesis_result': hypothesis_result,
    }
    return render(request, 'student_prediction/t_test_result.html', context)

def reading_scores_vs_gender(request):
    # Load the dataset from the 'data' folder
    dataset = pd.read_csv('data/stud.csv')

    # Perform the t-test for reading scores vs. gender
    gender = dataset['gender']
    reading_score = dataset['reading_score']

    t_test_result = stats.ttest_ind(reading_score[gender == 'male'], reading_score[gender == 'female'])
    
    female_mean = np.mean(reading_score[gender == 'female'])
    male_mean = np.mean(reading_score[gender == 'male']) 

    # Define null hypothesis (H0) and alternative hypothesis (H1)
    null_hypothesis = "There is no significant difference in the mean reading scores between male and female students."
    alternative_hypothesis = "There is a significant difference in the mean reading scores between male and female students."

    # Determine the result based on the p-value
    alpha = 0.05  # Set your significance level
    p_value = t_test_result.pvalue
    if p_value < alpha:
        hypothesis_result = "Reject H0"
    else:
        hypothesis_result = "Fail to Reject H0"

    context = {
        't_test_result': t_test_result,
        'test_name': "Reading Scores vs. Gender",
        'score': 'Reading',
        'female_mean':female_mean,
        'male_mean':male_mean,
        'null_hypothesis': null_hypothesis,
        'alternative_hypothesis': alternative_hypothesis,
        'hypothesis_result': hypothesis_result,
    }

student_performance_prediction/student_prediction/templates/student_prediction/prediction.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Performance Prediction</title>
    {% comment %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endcomment %}
</head>
<style>
    body {
        background: rgb(2,0,36);
        background: -moz-linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
        background: -webkit-linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
        background: linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#020024",endColorstr="#00d4ff",GradientType=1);
        font-family: Arial, sans-serif;
        margin: 0;
        /* Remove default margin to ensure full-width header and footer */
        padding: 0;
        /* Remove default padding */
    }

    /* Header styles */
    header {
        background-color: #333;
        padding: 2px 0;
        text-align: center;
        width: 100%;
    }
    header h1 a{
        color: #fff;
        text-decoration: none;
    }
    header h1 a:hover{
        color:red;
    }

    nav {
        background: red;
    }

    nav ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

    nav li {
        display: inline;
        margin-right: 20px;
    }

    nav li a {
        color: white;

    }

    /* Card styles */
    .container {
        display: flex;
        {% comment %} flex-wrap: wrap; {% endcomment %}
        justify-content: center;
        align-items: center;
        height: 100%;
        width:100%;
        {% comment %} background-color: red; {% endcomment %}
        margin-top:5em;
        /* Set container height to full viewport height */
    }

    .card {
        border: 1px solid #ccc;
        /* Add a border to the card */
        width: 300px;
        margin: 20px;
        text-align: center;
        border-radius: 5px;
        padding: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        background-color: #fffcf2;
        display: inline-block;
        vertical-align: top;
        /* Align cards to the top of the container */
        transition: transform 0.2s;
        /* Add a smooth hover effect */
    }

    .card img {
        max-width: 100%;
        border-radius: 5px;
    }

    .card h5 {
        font-size: 1.5rem;
        margin-top: 10px;
    }

    .card p {
        font-size: 1.2rem;
        margin: 10px 0;
        color: #023047; 
    }

    .card-button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007BFF;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
        font-weight: bold;
    }

    .card-button:hover {
        background-color: red;
    }


    /* Footer styles */
    footer {
        background-color: #333;
        color: #fff;
        padding: 0px 0px;
        text-align: center;
        position: fixed;
        bottom: 0;
        /* Stick to the bottom of the page */
        width: 100%;
    }

    /* Customize your CSS as needed */
</style>

<body>
    <header>
        <h1><a href="{% url 'base_page' %}">Student Performance Prediction</a></h1>
        {% comment %} <nav>
            <ul>
                <li><a href="{% url 'student_prediction:prediction' %}">Predictions1</a></li>
                <li><a href="{% url 'student_prediction2:prediction' %}">Predictions2</a></li>
                <li><a href="{% url 'student_prediction2:prediction' %}">Predictions2</a></li>
            </ul>
        </nav> {% endcomment %}
    </header>
    <div class="container">
        <div class="card" style="width: 18rem;">
            <img src="{% static 'images/math.jpg'%}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">MATHEMATICS</h5>
                <p class="card-text">Predict your Mathematics score and know your expected marka based on conditions.</p>
                <a href="{% url 'student_prediction:math_score' %}" class="card-button">Math Score</a>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <img src="{% static 'images/reading.jpg'%}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">READING</h5>
                <p class="card-text">Predict your Reading score and know your expected marka based on conditions.</p>
                <a href="{% url 'student_prediction:reading_score' %}" class="card-button">Reading Score</a>
            </div>
        </div>
            <div class="card" style="width: 18rem;">
                <img src="{% static 'images/writing.jpg'%}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">WRITING</h5>
                    <p class="card-text">Predict your Writing score and know your expected marka based on conditions.</p>
                    <a href="{% url 'student_prediction:writing_score' %}" class="card-button">Writing Score</a>
                </div>
            </div>
            {% comment %} {% block content %}{% endblock %} {% endcomment %}
        </div>
        <footer>
            <p>&copy; 2023 Student Performance Prediction</p>
        </footer>
</body>
</html>

student_performance_prediction/student_prediction/templates/student_prediction/prediction_anova.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Performance Prediction</title>
    {% comment %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endcomment %}
</head>
<style>
    body {
        background: rgb(2,0,36);
        background: -moz-linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
        background: -webkit-linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
        background: linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#020024",endColorstr="#00d4ff",GradientType=1);
        font-family: Arial, sans-serif;
        margin: 0;
        /* Remove default margin to ensure full-width header and footer */
        padding: 0;
        /* Remove default padding */
    }

    /* Header styles */
    header {
        background-color: #333;
        padding: 2px 0;
        text-align: center;
        width: 100%;
    }
    header h1 a{
        color: #fff;
        text-decoration: none;
    }
    header h1 a:hover{
        color:red;
    }

    nav {
        background: red;
    }

    nav ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

    nav li {
        display: inline;
        margin-right: 20px;
    }

    nav li a {
        color: white;

    }

    /* Card styles */
    .container {
        display: flex;
        {% comment %} flex-wrap: wrap; {% endcomment %}
        justify-content: center;
        align-items: center;
        height: 100%;
        width:100%;
        {% comment %} background-color: red; {% endcomment %}
        margin-top:5em;
        /* Set container height to full viewport height */
    }

    .card {
        border: 1px solid #ccc;
        /* Add a border to the card */
        width: 300px;
        margin: 20px;
        text-align: center;
        border-radius: 5px;
        padding: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        background-color: #fffcf2;
        display: inline-block;
        vertical-align: top;
        /* Align cards to the top of the container */
        transition: transform 0.2s;
        /* Add a smooth hover effect */
    }

    .card img {
        width: 300px; /* Set a specific width for the images */
        height: 270px; /* Maintain aspect ratio */
        border-radius: 5px;
    }
    

    .card h5 {
        font-size: 1.5rem;
        margin-top: 10px;
    }

    .card p {
        font-size: 1.2rem;
        margin: 10px 0;
        color: #023047; 
    }

    .card-button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007BFF;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
        font-weight: bold;
    }

    .card-button:hover {
        background-color: red;
    }


    /* Footer styles */
    footer {
        background-color: #333;
        color: #fff;
        padding: 0px 0px;
        text-align: center;
        position: fixed;
        bottom: 0;
        /* Stick to the bottom of the page */
        width: 100%;
    }

    /* Customize your CSS as needed */
</style>

<body>
    <header>
        <h1><a href="{% url 'base_page' %}">Student Performance Prediction</a></h1>
    </header>
    <div class="container">
        <div class="card" style="width: 18rem;">
                <img src="{% static 'images/reading.jpg'%}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Parental Education VS Reading Score</h5>
                    <p class="card-text">Is there any significant difference between Parental Education and reading scores ?</p>
                    <a href="{% url 'student_prediction:reading_scores_vs_parental_education' %}" class="card-button">Result</a>
                </div>
            </div>
        <div class="card" style="width: 18rem;">
                <img src="{% static 'images/writing.jpg'%}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Parental Education VS Writing Score</h5>
                    <p class="card-text">Is there any significant difference between Parental Education and writing scores ?</p>
                    <a href="{% url 'student_prediction:writing_scores_vs_parental_education' %}" class="card-button">Result</a>
                </div>
            </div>
        <div class="card" style="width: 18rem;">
                <img src="{% static 'images/math.jpg'%}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Parental Education VS Math Score</h5>
                    <p class="card-text">Is there any significant difference between Parental Education and math scores ?</p>
                    <a href="{% url 'student_prediction:math_scores_vs_parental_education' %}" class="card-button">Result</a>
                </div>
            </div>
            {% comment %} {% block content %}{% endblock %} {% endcomment %}
        </div>
        <footer>
            <p>&copy; 2023 Student Performance Prediction</p>
        </footer>
</body>

</html>