student_performance_prediction/student_performance_prediction/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.BasePageView.as_view(), name='base_page'),
    path('admin/', admin.site.urls),
    path('', include('student_prediction.urls')),
    path('', include('student_prediction2.urls')),
    # path('dashboard/', views.dash_app, name='dashboard'),  # Include the dashboard URLs
] + static(settings.MEDIA_URL, document_root =  settings.MEDIA_ROOT)

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

student_performance_prediction/student_prediction/urls.py
from django.urls import path
from . import views

app_name = 'student_prediction'

urlpatterns = [
    path('predictions/',views.prediction,name = 'prediction'),
    path('prediction_t_test/',views.prediction_t_test,name = 'prediction_t_test'),
    path('prediction_anova/',views.prediction_anova,name = 'prediction_anova'),
    path('writing_scores_vs_gender/', views.writing_scores_vs_gender, name='writing_scores_vs_gender'),
    path('reading_scores_vs_gender/', views.reading_scores_vs_gender, name='reading_scores_vs_gender'),
    path('math_scores_vs_gender/', views.math_scores_vs_gender, name='math_scores_vs_gender'),
    path('math_scores_vs_parental_education/', views.math_scores_vs_parental_education, name='math_scores_vs_parental_education'),
    path('reading_scores_vs_parental_education/', views.reading_scores_vs_parental_education, name='reading_scores_vs_parental_education'),
    path('writing_scores_vs_parental_education/', views.writing_scores_vs_parental_education, name='writing_scores_vs_parental_education'),
    path('predict_writing/', views.writing_score, name='writing_score'),
    path('predict_math/', views.math_score, name='math_score'),
    path('predict_reading/', views.reading_score, name='reading_score'),
]

student_performance_prediction/student_prediction2/urls.py
from django.urls import path
from . import views

app_name = 'student_prediction2'

urlpatterns = [
    path('predictions2/',views.prediction,name = 'prediction'),
    path('predict_performance_index/', views.predict_performance_index, name='predict_performance_index'),
    path('scatter_plot/', views.scatter_plot, name='scatter_plot'),
]

student_performance_prediction/student_prediction2/models.py
from django.db import models

class Student2(models.Model):
    hours_studied = models.IntegerField()
    previous_scores = models.IntegerField()
    extracurricular_activities = models.CharField(max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')])
    sleep_hours = models.IntegerField()
    sample_question_papers_practiced = models.IntegerField()
    performance_index = models.FloatField()

    def __str__(self):
        return f'Student2 {self.pk}'

student_performance_prediction/student_prediction2/forms.py
from django import forms

# Performance Index
class performance_index_form(forms.Form):
    hours_studied = forms.IntegerField(label='Hours Studied', min_value=0)
    previous_scores = forms.IntegerField(label='Previous Scores', min_value=0)
    extracurricular_activities = forms.ChoiceField(
        choices=[(1, 'Yes'), (0, 'No')],
        label='Extracurricular Activities (1 for Yes and 0 for No)'
    )
    sleep_hours = forms.IntegerField(label='Sleep Hours', min_value=0)
    sample_question_papers_practiced = forms.IntegerField(
        label='Sample Question Papers Practiced', min_value=0
    )

student_performance_prediction/student_prediction2/views.py
# student_prediction2/views.py
import pandas as pd
import joblib
from django.shortcuts import render
from .forms import performance_index_form
import pandas as pd
import matplotlib.pyplot as plt
from django.http import HttpResponse
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#Model Path 
MODEL_PATH1 = os.path.join(BASE_DIR,'ml_models','best_student_performance_model4.pkl')

# Data Path
DATA_PATH = os.path.join(BASE_DIR,'data','updated_preprocessed_dataset2.csv')



# Loading the Model
model1 = joblib.load(MODEL_PATH1)


# Create your views here.
def prediction(request):
    # You can add any necessary logic here, if needed
    return render(request, 'student_prediction2/prediction.html')

def predict_performance_index(request):
    dataset = pd.read_csv(DATA_PATH)
    
    
    if request.method == 'POST':
        form  = performance_index_form(request.POST)
        if form.is_valid():
            
            # Get user input from the form
            input_data = form.cleaned_data
            
            # Create a DataFrame with user input
            user_data = pd.DataFrame([input_data])
            
            # Define a dictionary to map old column names to new names
            column_mapping = {
                'hours_studied': 'Hours Studied',
                'previous_scores': 'Previous Scores',
                'extracurricular_activities': 'Extracurricular Activities',
                'sleep_hours': 'Sleep Hours',
                'sample_question_papers_practiced': 'Sample Question Papers Practiced'
            }

            # Rename the columns in user_data
            user_data.rename(columns=column_mapping, inplace=True)
            
            # Make predictions using model and store it in variable
            predicted_performance = round(model1.predict(user_data)[0],2)
            
            # Append user_data to the dataset
            dataset = pd.concat([dataset, user_data], ignore_index=True)
                
            # Save the updated Dataset
            dataset.to_csv(DATA_PATH,index = False)

            return render(request,'student_prediction2/prediction_result.html',{'predicted_performance':predicted_performance})
    
    else:
        form= performance_index_form()
        
    return render(request,'student_prediction2/user_input_form.html',{'form':form})



def scatter_plot(request):
    # Read the CSV file into a DataFrame
    df = pd.read_csv(DATA_PATH)

    # Extract data columns from the DataFrame
    hours_studied = df['Hours Studied']
    previous_scores = df['Previous Scores']
    
    # Create a scatter plot
    plt.figure(figsize=(8, 6))
    plt.scatter(hours_studied, previous_scores, c='blue', marker='o', alpha=0.5)
    plt.title('Scatter Plot of Hours Studied vs. Previous Scores')
    plt.xlabel('Hours Studied')
    plt.ylabel('Previous Scores')
    
    image_path = os.path.join(BASE_DIR,'static/images','scatter_plot.png')
    
    # Save the plot as an image file (optional)
    plt.savefig(image_path)

    context = {'scatter_plot_image':image_path}

    
    return render(request,'student_prediction2/prediction_result.html',context)

student_performance_prediction/student_prediction2/templates/student_prediction2/prediction.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Performance Prediction</title>
    {% comment %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endcomment %}
</head>
<style>
    body {
        background: rgb(2,0,36);
        background: -moz-linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
        background: -webkit-linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
        background: linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#020024",endColorstr="#00d4ff",GradientType=1);
        font-family: Arial, sans-serif;
        margin: 0;
        /* Remove default margin to ensure full-width header and footer */
        padding: 0;
        /* Remove default padding */
    }

    /* Header styles */
    header {
        background-color: #333;
        {% comment %} color: #fff; {% endcomment %}
        padding: 2px 0;
        text-align: center;
        width: 100%;
    }
    
    header h1 a{
        color: #fff;
        text-decoration: none;
    }
    header h1 a:hover{
        color:red;
    }


    nav {
        background: red;
    }

    nav ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

    nav li {
        display: inline;
        margin-right: 20px;
    }

    nav li a {
        color: white;

    }

    /* Card styles */
    .container {
        display: flex;
        {% comment %} flex-wrap: wrap; {% endcomment %}
        justify-content: center;
        align-items: center;
        height: 100%;
        width:100%;
        {% comment %} background-color: red; {% endcomment %}
        margin-top:2em;
        /* Set container height to full viewport height */
    }

    .card {
        border: 1px solid #ccc;
        /* Add a border to the card */
        width: 300px;
        margin: 20px;
        text-align: center;
        border-radius: 5px;
        padding: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        background-color: #fff;
        display: inline-block;
        vertical-align: top;
        /* Align cards to the top of the container */
        transition: transform 0.2s;
        /* Add a smooth hover effect */
    }

    .card img {
        max-width: 100%;
        border-radius: 5px;
    }

    .card h5 {
        font-size: 1.5rem;
        margin-top: 10px;
    }

    .card p {
        font-size: 1.2rem;
        margin: 10px 0;
        color: #023047; 
    }

    .card-button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007BFF;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
        font-weight: bold;
    }

    .card-button:hover {
        background-color: red;
    }


    /* Footer styles */
    footer {
        background-color: #333;
        color: #fff;
        padding: 0px 0px;
        text-align: center;
        position: absolute;
        bottom: 0;
        /* Stick to the bottom of the page */
        width: 100%;
    }

    /* Customize your CSS as needed */
</style>

<body>
    <header>
        <h1><a href="{% url 'base_page' %}">Student Performance Prediction</a></h1>
        {% comment %} <nav>
            <ul>
                <li><a href="{% url 'student_prediction:prediction' %}">Predictions1</a></li>
                <li><a href="{% url 'student_prediction2:prediction' %}">Predictions2</a></li>
                <li><a href="{% url 'student_prediction2:prediction' %}">Predictions2</a></li>
            </ul>
        </nav> {% endcomment %}
    </header>
    <div class="container">
        <div class="card" style="width: 18rem;">
            <img src="{% static 'images/performance.jpg'%}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Performance</h5>
                <p class="card-text">Predict your performance scorebased on previous scores and other conditions.</p>
                <a href="{% url 'student_prediction2:predict_performance_index' %}" class="card-button">Predict Performance Score</a>
            </div>
        </div>
        {% comment %} <div class="card" style="width: 18rem;">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
                <a href="{% url 'student_prediction:reading_score' %}" class="card-button">Reading Score</a>
            </div>
        </div>
            <div class="card" style="width: 18rem;">
                <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                        card's content.</p>
                    <a href="{% url 'student_prediction:writing_score' %}" class="card-button">Writing Score</a>
                </div>
            </div> {% endcomment %}
            {% comment %} {% block content %}{% endblock %} {% endcomment %}
        </div>
        <footer>
            <p>&copy; 2023 Student Performance Prediction</p>
        </footer>
</body>

</html>

student_performance_prediction/student_prediction2/templates/student_prediction2/prediction_result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Performance Prediction</title>
    {% comment %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endcomment %}
</head>
<style>
    body {
        background: rgb(2,0,36);
        background: -moz-linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
        background: -webkit-linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
        background: linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#020024",endColorstr="#00d4ff",GradientType=1);
        font-family: Arial, sans-serif;
        margin: 0;
        /* Remove default margin to ensure full-width header and footer */
        padding: 0;
        /* Remove default padding */
    }

    /* Header styles */
    header {
        background-color: #333;
        {% comment %} color: #fff; {% endcomment %}
        padding: 2px 0;
        text-align: center;
        width: 100%;
    }
    header h1 a{
        color: #fff;
        text-decoration: none;
    }
    header h1 a:hover{
        color:red;
    }


    nav {
        background: red;
    }

    nav ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

    nav li {
        display: inline;
        margin-right: 20px;
    }

    nav li a {
        color: white;

    }

    /* Card styles */
    .container {
        display: flex;
        {% comment %} flex-wrap: wrap; {% endcomment %}
        justify-content: center;
        align-items: center;
        height: 100%;
        width:100%;
        {% comment %} background-color: red; {% endcomment %}
        margin-top:2em;
        /* Set container height to full viewport height */
    }

    .card {
        border: 1px solid #ccc;
        /* Add a border to the card */
        width: 300px;
        margin: 20px;
        text-align: center;
        border-radius: 5px;
        padding: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        background-color: #fff;
        display: inline-block;
        vertical-align: top;
        /* Align cards to the top of the container */
        transition: transform 0.2s;
        /* Add a smooth hover effect */
    }

    .card img {
        max-width: 100%;
        border-radius: 5px;
    }

    .card h3 {
        font-size: 1.5rem;
        margin-top: 10px;
        text-decoration: underline;
    }

    .card p {
        font-size: 1.2rem;
        margin: 10px 0;
        color: red; 
        font-weight:bold;  
    }

    .card-button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007BFF;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
        font-weight: bold;
    }

    .card-button:hover {
        background-color: black;
    }


    /* Footer styles */
    footer {
        background-color: #333;
        color: #fff;
        padding: 10px 0;
        text-align: center;
        position: absolute;
        bottom: 0;
        /* Stick to the bottom of the page */
        width: 100%;
    }

    /* Customize your CSS as needed */
</style>

<body>
    <header>
        <h1><a href="{% url 'base_page' %}">Student Performance Prediction</a></h1>
    </header>
    <div class="container">
        <div class="card" style="width: 18rem;">
            <img src="{% static 'images/result.jpg'%}" class="card-img-top" alt="...">
            <div class="card-body">
                <h3 class="card-title">Prediction Result</h3>
                <p class="card-text"> Your Predicted Performance is: {{predicted_performance}}</p>
                <a href="{% url 'student_prediction2:prediction' %}" class="card-button">Back to Prediction</a>
            </div>
        </div>
        {% comment %} <div class="card" style="width: 18rem;">
            <img src="{% static scatter_plot_image %}" class="card-img-top" alt="Scatter Plot">
            <div class="card-body">
                <h5 class="card-title">Scatter Plot</h5>
                

            </div>
        </div> {% endcomment %}
        </div>
        <footer>
            <p>&copy; 2023 Student Performance Prediction</p>
        </footer>
</body>

</html>

student_performance_prediction/student_prediction2/templates/student_prediction2/user_input_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Student Performance Prediction</title>
    <link rel="stylesheet" href="{% static 'css/style1.css' %}" />
    <!-- Add this to your HTML template -->
  </head>
  <style>
        body {
            background: rgb(2,0,36);
            background: -moz-linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
            background: -webkit-linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
            background: linear-gradient(90deg, rgba(2,0,36,1) 7%, rgba(87,87,214,1) 53%, rgba(0,212,255,1) 86%);
            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#020024",endColorstr="#00d4ff",GradientType=1);
            font-family: Arial, sans-serif;
            margin: 0; /* Remove default margin to ensure full-width header and footer */
            padding: 0; /* Remove default padding */
        }

        /* Header styles */
        header {
            background-color: #333;
            {% comment %} color: #fff; {% endcomment %}
            padding: 2px 0;
            text-align: center;
        }
        header h1 a{
            color: #fff;
            text-decoration: none;
        }
        header h1 a:hover{
            color:red;
        }
        /* Card styles */
        .container {
            display: flex;
            {% comment %} flex-wrap: wrap; {% endcomment %}
            justify-content: center;
            align-items: center;
            height: auto;
            width:100%;
            {% comment %} background-color: red; {% endcomment %}
            margin-top:2em;
            /* Set container height to full viewport height */
        }       
        
    /* Footer styles */
        footer {
            background-color: #333;
            color: #fff;
            padding: 0px 0;
            text-align: center;
            position: absolute;
            bottom: -7em; /* Stick to the bottom of the page */
            width: 100%;
        }

  </style>
  <body>
    <header>
      <h1>
        <a href="{% url 'student_prediction2:prediction' %}"
          >Performance Prediction</a
        >
      </h1>
    </header>
    <div class="container">
      <div class="form-scroll-container">
        <div class="form-container">
          <h1 class="form-heading">Predict Performance</h1>
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="{{ form.hours_studied.id_for_label }}"
                >Hour Studied</label
              >
              {{ form.hours_studied }}
            </div>
            <div class="form-group">
              <label for="{{ form.previous_scores.id_for_label }}"
                >Previous Scores</label
              >
              {{ form.previous_scores }}
            </div>
            <div class="form-group">
              <label for="{{ form.extracurricular_activities.id_for_label }}"
                >Extra Curricular Activities</label
              >
              {{ form.extracurricular_activities }}
            </div>
            <div class="form-group">
              <label for="{{ form.sleep_hours.id_for_label }}"
                >Sleep Hours
              </label>
              {{ form.sleep_hours }}
            </div>
            <div class="form-group">
              <label
                for="{{ form.sample_question_papers_practiced.id_for_label }}"
                >Sample Questions Practiced</label
              >
              {{ form.sample_question_papers_practiced }}
            </div>
            <button type="submit" class="btn-submit">Predict</button>
          </form>
        </div>
      </div>
    </div>
    <footer>
      <p>&copy; 2023 Student Performance Prediction</p>
    </footer>
  </body>
</html>